import type { User, Anchor, Dealer, Supplier, Task, ActivityLog } from './types';

export const mockUsers: User[] = [
  { uid: 'user-1', name: 'Ramesh Kumar', email: 'ramesh@supermoney.in', role: 'Sales' },
  { uid: 'user-2', name: 'Priya Sharma', email: 'priya@supermoney.in', role: 'Sales' },
  { uid: 'user-admin', name: 'Admin User', email: 'admin@supermoney.in', role: 'Admin' },
];

export const mockAnchors: Anchor[] = [
  { 
    id: 'anchor-1', 
    name: 'Reliance Retail', 
    industry: 'Retail',
    status: 'Active',
    primaryContactName: 'Anil Mehta',
    email: 'anil.mehta@reliance.com',
    contactNumber: '9876543210',
    assignedTo: 'user-1',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    dealerIds: ['dealer-1'],
    supplierIds: ['supplier-1'],
    annualTurnover: 5000000000,
    gstin: '27AACCR1234A1Z5',
    creditRating: 'AAA',
    address: 'Reliance Corporate Park, Ghansoli, Navi Mumbai, Maharashtra 400701',
    leadSource: 'Banker Referral',
    leadScore: 95,
    leadScoreReason: "High turnover, strong credit rating, and strategic industry make this a prime lead."
  },
  { 
    id: 'anchor-2', 
    name: 'Tata Motors', 
    industry: 'Automotive',
    status: 'Proposal',
    primaryContactName: 'Sunita Rao',
    email: 'sunita.rao@tatamotors.com',
    contactNumber: '9876543211',
    assignedTo: 'user-1',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    dealerIds: [],
    supplierIds: [],
    leadSource: 'Conference / Event',
  },
  { 
    id: 'anchor-3', 
    name: 'Apollo Tyres', 
    industry: 'Automotive',
    status: 'Negotiation',
    primaryContactName: 'Vijay Singh',
    email: 'vijay.s@apollotyres.com',
    contactNumber: '9876543212',
    assignedTo: 'user-2',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    dealerIds: [],
    supplierIds: [],
    leadSource: 'LinkedIn Campaign',
  },
  { 
    id: 'anchor-4', 
    name: 'Future Group', 
    industry: 'Retail',
    status: 'Lead',
    primaryContactName: 'Kishore Biyani',
    email: 'kb@futuregroup.in',
    contactNumber: '9876543213',
    assignedTo: 'user-2',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    dealerIds: [],
    supplierIds: [],
    leadSource: 'Website Inquiry',
  },
  { 
    id: 'anchor-5', 
    name: 'Unassigned Corp', 
    industry: 'Manufacturing',
    status: 'Unassigned Lead',
    primaryContactName: 'John Doe',
    email: 'john.doe@unassigned.com',
    contactNumber: '9999999999',
    assignedTo: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    dealerIds: [],
    supplierIds: [],
    leadSource: 'Referral',
  },
];

export const mockDealers: Dealer[] = [
  { id: 'dealer-1', name: 'Mumbai Motors', contactNumber: '9123456780', onboardingStatus: 'Active', anchorId: 'anchor-1', assignedTo: 'user-1', createdAt: new Date().toISOString() },
  { id: 'dealer-2', name: 'Pune Auto', contactNumber: '9123456781', onboardingStatus: 'Invited', anchorId: 'anchor-2', assignedTo: 'user-1', createdAt: new Date().toISOString() },
  { id: 'dealer-3', name: 'Delhi Dealers', contactNumber: '9123456782', onboardingStatus: 'Unassigned Lead', anchorId: null, assignedTo: null, createdAt: new Date().toISOString(), location: 'Delhi' },
];

export const mockSuppliers: Supplier[] = [
  { id: 'supplier-1', name: 'Shree Krishna Parts', contactNumber: '8123456780', onboardingStatus: 'Active', anchorId: 'anchor-1', assignedTo: 'user-1', createdAt: new Date().toISOString() },
  { id: 'supplier-2', name: 'Balaji Components', contactNumber: '8123456781', onboardingStatus: 'KYC Pending', anchorId: 'anchor-1', assignedTo: 'user-1', createdAt: new Date().toISOString() },
  { id: 'supplier-3', name: 'Unassigned Suppliers Inc', contactNumber: '8123456782', onboardingStatus: 'Unassigned Lead', anchorId: null, assignedTo: null, createdAt: new Date().toISOString(), location: 'Chennai' },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Follow up on Proposal V2',
    associatedWith: { anchorId: 'anchor-2' },
    type: 'Call',
    dueDate: new Date().toISOString(),
    priority: 'High',
    description: 'Check status of the proposal sent last week.',
    status: 'To-Do',
    assignedTo: 'user-1',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-2',
    title: 'Prepare for negotiation meeting',
    associatedWith: { anchorId: 'anchor-3' },
    type: 'Proposal Preparation',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'High',
    description: 'Get all the figures and final terms ready.',
    status: 'In Progress',
    assignedTo: 'user-2',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-3',
    title: 'Initial contact call',
    associatedWith: { anchorId: 'anchor-4' },
    type: 'Call',
    dueDate: new Date().toISOString(),
    priority: 'Medium',
    description: 'First call to qualify the lead from website.',
    status: 'To-Do',
    assignedTo: 'user-2',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-4',
    title: 'Send welcome kit to Mumbai Motors',
    associatedWith: { anchorId: 'anchor-1', dealerId: 'dealer-1' },
    type: 'Email',
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    priority: 'Low',
    description: 'Welcome kit for the newly onboarded dealer.',
    status: 'Completed',
    assignedTo: 'user-1',
    createdAt: new Date().toISOString(),
  },
];

export const mockActivityLogs: ActivityLog[] = [
    {
        id: 'log-1',
        anchorId: 'anchor-1',
        timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        type: 'Email',
        title: "Proposal sent to 'Reliance Retail'",
        outcome: "Proposal V1 sent to Anil Mehta. Acknowledged receipt.",
        userName: 'Ramesh Kumar',
    },
    {
        id: 'log-2',
        anchorId: 'anchor-1',
        timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        type: 'Meeting (Online)',
        title: "'ABC Corp' moved to Onboarding",
        outcome: "Deal won. Moved to onboarding stage. Onboarding specialist notified.",
        userName: 'Ramesh Kumar',
    },
    {
        id: 'log-3',
        anchorId: 'anchor-2',
        timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        type: 'Call',
        title: "Call logged with John Doe at 'Tata Motors'",
        outcome: "Discussed initial requirements. Client is interested in supplier finance.",
        userName: 'Priya Sharma',
    }
];
